[2025-06-07T19:13:52.339+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T18:30:00+00:00 [queued]>
[2025-06-07T19:13:52.345+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T18:30:00+00:00 [queued]>
[2025-06-07T19:13:52.345+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-06-07T19:13:52.353+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_producer_one_file> on 2025-06-07 18:30:00+00:00
[2025-06-07T19:13:52.356+0000] {standard_task_runner.py:60} INFO - Started process 295 to run task
[2025-06-07T19:13:52.358+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'producer_dag', 'run_producer_one_file', 'scheduled__2025-06-07T18:30:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpj6h38mec']
[2025-06-07T19:13:52.359+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask run_producer_one_file
[2025-06-07T19:13:52.384+0000] {task_command.py:423} INFO - Running <TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T18:30:00+00:00 [running]> on host 42aec07446f7
[2025-06-07T19:13:52.419+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='producer_dag' AIRFLOW_CTX_TASK_ID='run_producer_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T18:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T18:30:00+00:00'
[2025-06-07T19:13:52.419+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-07T19:13:52.420+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/kafka_client/producer_one_shot.py']
[2025-06-07T19:13:52.424+0000] {subprocess.py:86} INFO - Output:
[2025-06-07T19:13:52.437+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/kafka_client/producer_one_shot.py': [Errno 2] No such file or directory
[2025-06-07T19:13:52.438+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-07T19:13:52.444+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-07T19:13:52.446+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=producer_dag, task_id=run_producer_one_file, execution_date=20250607T183000, start_date=20250607T191352, end_date=20250607T191352
[2025-06-07T19:13:52.451+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task run_producer_one_file (Bash command failed. The command returned a non-zero exit code 2.; 295)
[2025-06-07T19:13:52.496+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-07T19:13:52.505+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
