[2025-06-10T12:29:19.111+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-10T12:29:19.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.run_consumer scheduled__2025-06-10T12:20:00+00:00 [queued]>
[2025-06-10T12:29:19.152+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.run_consumer scheduled__2025-06-10T12:20:00+00:00 [queued]>
[2025-06-10T12:29:19.152+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-10T12:29:19.159+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_consumer> on 2025-06-10 12:20:00+00:00
[2025-06-10T12:29:19.165+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10010) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-10T12:29:19.166+0000] {standard_task_runner.py:63} INFO - Started process 10013 to run task
[2025-06-10T12:29:19.167+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_pipeline_branching_dag', 'run_consumer', 'scheduled__2025-06-10T12:20:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/kafka_pipeline_dag.py', '--cfg-path', '/tmp/tmpasqm7f5h']
[2025-06-10T12:29:19.168+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask run_consumer
[2025-06-10T12:29:19.202+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_pipeline_branching_dag.run_consumer scheduled__2025-06-10T12:20:00+00:00 [running]> on host 4e91ff50f4f4
[2025-06-10T12:29:19.261+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_pipeline_branching_dag' AIRFLOW_CTX_TASK_ID='run_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-10T12:20:00+00:00'
[2025-06-10T12:29:19.262+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-10T12:29:19.270+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-10T12:29:19.271+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'timeout 300 python /opt/***/kafka_client/consumer.py > /opt/***/logs/consumer_output.log 2>&1']
[2025-06-10T12:29:19.280+0000] {subprocess.py:86} INFO - Output:
[2025-06-10T12:34:19.343+0000] {subprocess.py:97} INFO - Command exited with return code 124
[2025-06-10T12:34:19.354+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-10T12:34:19.383+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 124.
[2025-06-10T12:34:19.391+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_pipeline_branching_dag, task_id=run_consumer, run_id=scheduled__2025-06-10T12:20:00+00:00, execution_date=20250610T122000, start_date=20250610T122919, end_date=20250610T123419
[2025-06-10T12:34:19.405+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task run_consumer (Bash command failed. The command returned a non-zero exit code 124.; 10013)
[2025-06-10T12:34:19.443+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-10T12:34:19.453+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
