[2025-06-08T06:57:30.465+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T06:57:30.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer_dag.check_kafka_connection manual__2025-06-08T06:57:29.501759+00:00 [queued]>
[2025-06-08T06:57:30.498+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer_dag.check_kafka_connection manual__2025-06-08T06:57:29.501759+00:00 [queued]>
[2025-06-08T06:57:30.499+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-08T06:57:30.511+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_kafka_connection> on 2025-06-08 06:57:29.501759+00:00
[2025-06-08T06:57:30.520+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'producer_dag', 'check_kafka_connection', 'manual__2025-06-08T06:57:29.501759+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpcebd8ibv']
[2025-06-08T06:57:30.524+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask check_kafka_connection
[2025-06-08T06:57:30.532+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-08T06:57:30.532+0000] {standard_task_runner.py:63} INFO - Started process 181 to run task
[2025-06-08T06:57:30.566+0000] {task_command.py:426} INFO - Running <TaskInstance: producer_dag.check_kafka_connection manual__2025-06-08T06:57:29.501759+00:00 [running]> on host 5492e8ecb5c1
[2025-06-08T06:57:30.627+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='producer_dag' AIRFLOW_CTX_TASK_ID='check_kafka_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T06:57:29.501759+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T06:57:29.501759+00:00'
[2025-06-08T06:57:30.628+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T06:57:30.646+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T06:57:30.647+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/producer_dag.py", line 17, in check_kafka_connection
    broker = os.getenv('KAFKA_BROKER', 'kafka:29092')
             ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-06-08T06:57:30.653+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=producer_dag, task_id=check_kafka_connection, run_id=manual__2025-06-08T06:57:29.501759+00:00, execution_date=20250608T065729, start_date=20250608T065730, end_date=20250608T065730
[2025-06-08T06:57:30.658+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task check_kafka_connection (name 'os' is not defined; 181)
[2025-06-08T06:57:30.674+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T06:57:30.685+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T06:57:30.686+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
