[2025-06-08T15:00:03.768+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T15:00:03.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.fail_if_es_down_too_long scheduled__2025-06-08T14:30:00+00:00 [queued]>
[2025-06-08T15:00:03.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.fail_if_es_down_too_long scheduled__2025-06-08T14:30:00+00:00 [queued]>
[2025-06-08T15:00:03.814+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T15:00:03.831+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fail_if_es_down_too_long> on 2025-06-08 14:30:00+00:00
[2025-06-08T15:00:03.844+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2502) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-08T15:00:03.851+0000] {standard_task_runner.py:63} INFO - Started process 2503 to run task
[2025-06-08T15:00:03.845+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'master_pipeline_with_es_guard', 'fail_if_es_down_too_long', 'scheduled__2025-06-08T14:30:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpq5s6koo7']
[2025-06-08T15:00:03.860+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask fail_if_es_down_too_long
[2025-06-08T15:00:03.938+0000] {task_command.py:426} INFO - Running <TaskInstance: master_pipeline_with_es_guard.fail_if_es_down_too_long scheduled__2025-06-08T14:30:00+00:00 [running]> on host 5492e8ecb5c1
[2025-06-08T15:00:04.019+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='master_pipeline_with_es_guard' AIRFLOW_CTX_TASK_ID='fail_if_es_down_too_long' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:30:00+00:00'
[2025-06-08T15:00:04.020+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T15:00:04.038+0000] {logging_mixin.py:188} INFO - üìä ES failure count: 5
[2025-06-08T15:00:04.039+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T15:00:04.042+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/producer_dag.py", line 70, in fail_if_es_down_too_long
    raise Exception("‚ùå ES has been down too long.")
Exception: ‚ùå ES has been down too long.
[2025-06-08T15:00:04.067+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=master_pipeline_with_es_guard, task_id=fail_if_es_down_too_long, run_id=scheduled__2025-06-08T14:30:00+00:00, execution_date=20250608T143000, start_date=20250608T150003, end_date=20250608T150004
[2025-06-08T15:00:04.084+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task fail_if_es_down_too_long (‚ùå ES has been down too long.; 2503)
[2025-06-08T15:00:04.122+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T15:00:04.152+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T15:00:04.153+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
