[2025-06-07T21:30:43.349+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-07T21:30:43.384+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T21:00:00+00:00 [queued]>
[2025-06-07T21:30:43.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T21:00:00+00:00 [queued]>
[2025-06-07T21:30:43.395+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-06-07T21:30:43.402+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_producer_one_file> on 2025-06-07 21:00:00+00:00
[2025-06-07T21:30:43.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=259) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-07T21:30:43.407+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'producer_dag', 'run_producer_one_file', 'scheduled__2025-06-07T21:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmp7glespz_']
[2025-06-07T21:30:43.408+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask run_producer_one_file
[2025-06-07T21:30:43.408+0000] {standard_task_runner.py:63} INFO - Started process 263 to run task
[2025-06-07T21:30:43.438+0000] {task_command.py:426} INFO - Running <TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T21:00:00+00:00 [running]> on host fcf6efcc464d
[2025-06-07T21:30:43.480+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='producer_dag' AIRFLOW_CTX_TASK_ID='run_producer_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T21:00:00+00:00'
[2025-06-07T21:30:43.481+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-07T21:30:43.489+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-07T21:30:43.490+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/kafka_client/producer_one_shot.py']
[2025-06-07T21:30:43.495+0000] {subprocess.py:86} INFO - Output:
[2025-06-07T21:30:44.074+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-07T21:30:44.074+0000] {subprocess.py:93} INFO -   File "/opt/***/kafka_client/producer_one_shot.py", line 6, in <module>
[2025-06-07T21:30:44.074+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-06-07T21:30:44.074+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
[2025-06-07T21:30:44.075+0000] {subprocess.py:93} INFO -     from kafka.consumer import KafkaConsumer
[2025-06-07T21:30:44.075+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
[2025-06-07T21:30:44.075+0000] {subprocess.py:93} INFO -     from kafka.consumer.group import KafkaConsumer
[2025-06-07T21:30:44.075+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
[2025-06-07T21:30:44.075+0000] {subprocess.py:93} INFO -     from kafka.consumer.fetcher import Fetcher
[2025-06-07T21:30:44.076+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
[2025-06-07T21:30:44.076+0000] {subprocess.py:93} INFO -     from kafka.record import MemoryRecords
[2025-06-07T21:30:44.076+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
[2025-06-07T21:30:44.076+0000] {subprocess.py:93} INFO -     from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
[2025-06-07T21:30:44.076+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
[2025-06-07T21:30:44.076+0000] {subprocess.py:93} INFO -     from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
[2025-06-07T21:30:44.076+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
[2025-06-07T21:30:44.077+0000] {subprocess.py:93} INFO -     from kafka.codec import (
[2025-06-07T21:30:44.077+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
[2025-06-07T21:30:44.077+0000] {subprocess.py:93} INFO -     from kafka.vendor.six.moves import range
[2025-06-07T21:30:44.077+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
[2025-06-07T21:30:44.142+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-07T21:30:44.142+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-07T21:30:44.151+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-07T21:30:44.154+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=producer_dag, task_id=run_producer_one_file, run_id=scheduled__2025-06-07T21:00:00+00:00, execution_date=20250607T210000, start_date=20250607T213043, end_date=20250607T213044
[2025-06-07T21:30:44.162+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task run_producer_one_file (Bash command failed. The command returned a non-zero exit code 1.; 263)
[2025-06-07T21:30:44.167+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-07T21:30:44.176+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-07T21:30:44.177+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
