[2025-06-08T15:00:01.803+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T15:00:01.847+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.run_producer scheduled__2025-06-08T14:30:00+00:00 [queued]>
[2025-06-08T15:00:01.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.run_producer scheduled__2025-06-08T14:30:00+00:00 [queued]>
[2025-06-08T15:00:01.865+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T15:00:01.895+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_producer> on 2025-06-08 14:30:00+00:00
[2025-06-08T15:00:01.917+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2479) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-08T15:00:01.915+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'master_pipeline_with_es_guard', 'run_producer', 'scheduled__2025-06-08T14:30:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpgu012bxc']
[2025-06-08T15:00:01.920+0000] {standard_task_runner.py:63} INFO - Started process 2483 to run task
[2025-06-08T15:00:01.920+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask run_producer
[2025-06-08T15:00:02.159+0000] {task_command.py:426} INFO - Running <TaskInstance: master_pipeline_with_es_guard.run_producer scheduled__2025-06-08T14:30:00+00:00 [running]> on host 5492e8ecb5c1
[2025-06-08T15:00:02.270+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='master_pipeline_with_es_guard' AIRFLOW_CTX_TASK_ID='run_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:30:00+00:00'
[2025-06-08T15:00:02.272+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T15:00:02.293+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T15:00:02.295+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/kafka_client/producer_one_shot.py']
[2025-06-08T15:00:02.311+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T15:03:28.294+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-06-08T15:03:28.297+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-08T15:03:28.301+0000] {process_utils.py:132} INFO - Sending 15 to group 2483. PIDs of all processes in the group: [2485, 2483]
[2025-06-08T15:03:28.302+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2483
[2025-06-08T15:03:28.304+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-08T15:03:28.307+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-08T15:03:28.309+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T15:03:28.330+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-08T15:03:28.336+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=master_pipeline_with_es_guard, task_id=run_producer, run_id=scheduled__2025-06-08T14:30:00+00:00, execution_date=20250608T143000, start_date=20250608T150001, end_date=20250608T150328
[2025-06-08T15:03:28.358+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task run_producer ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(master_pipeline_with_es_guard, run_producer, scheduled__2025-06-08T14:30:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_producer', 'dag_id': 'master_pipeline_with_es_guard', 'run_id': 'scheduled__2025-06-08T14:30:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 6, 8, 15, 0, 1, 847543, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 6, 8, 15, 3, 28, 335613, tzinfo=Timezone('UTC')), 'duration': 206}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2483)
[2025-06-08T15:03:28.403+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2483, status='terminated', exitcode=1, started='15:00:01') (2483) terminated with exit code 1
[2025-06-08T15:03:28.404+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2485, status='terminated', started='15:00:01') (2485) terminated with exit code None
